file = entries table*

table = head entries
entries = ( entry ( entrysep entry )* entrysep? )?
entrysep = NL | ";"
head = "[" keypath "]" NL | "[[" keypath "]]" NL
keypath = ( key "." )* key
entry = keypath "=" value? NL

value = tag? tagless # note mandatory tag adjacency to [ { ' "
tagless = array | object | number | string | boolean
array = "[" value ( "," value )* ","? "]"
object = "{" keyvalue ( "," keyvalue )* ","? "}"
keyvalue = key ":" value
boolean = "true" | "false" | "yes" | "no" | "on" | "off" | "T" | "F" | "Y" | "N"

tag = IDENT
type = IDENT
key = IDENT | string | number
number = FLOAT | DECINT | HEXINT | OCTINT
string = SINGLE_STRING | DOUBLE_STRING | TRIPLE_SINGLE_STRING | TRIPLE_DOUBLE_STRING
