toplevel = entry* table* | value

table = head entry*
head = "[" keypath "]" | "[[" keypath "]]"
keypath = ( key "." )* key
entry = keypath "=" value

value = ( tag ":" )* untagged
untagged = array | object | number | string | boolean
array = "[" value ( "," value )* ","? "]"
object = "{" value ( "," value )* ","? "}"
boolean = "true" | "false"

tag = IDENT
key = IDENT | string | number
number = FLOAT | INT
string = SINGLE_STRING | DOUBLE_STRING | TRIPLE_SINGLE_STRING | TRIPLE_DOUBLE_STRING
